# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T19:38:38+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Status(Enum):
    ok = 'ok'
    error = 'error'


class Bng2latlongEastingNorthingGetResponse(BaseModel):
    easting: Optional[int] = Field(None, examples=[326897])
    error: Optional[str] = Field(
        None,
        examples=[
            'Both <easting> and <northing> must be provided, must be positive integers, and must be within range.'
        ],
    )
    latitude: Optional[float] = Field(None, examples=[55.95271])
    longitude: Optional[float] = Field(None, examples=[-3.17227])
    northing: Optional[int] = Field(None, examples=[673919])
    status: Optional[Status] = None
